sudo: false
language: node_js
node_js:
  - 8
os:
  - linux
before_install:
  - npm i -g npm@6.0.1
  - npm --version
install:
  - npm ci
  - npm run load-apps
before_script:
  - if [[ "$TRAVIS_BRANCH" == "develop" ]]; then npm run doc; fi
script:
  - ./.concourse/test.sh
