language: node_js
node_js:
- 4.3.0
before_script:
- export DISPLAY=:99.0; sh -e /etc/init.d/xvfb start
- npm i -g babel-cli
- npm i -g asar
before_deploy:
- cp /scripts/builds/index.js /src/js/pages/index.js
- babel src --out-dir src
- node scripts/builds/build-win.js
- echo Extracting app.asar
- asar extract ./dist/translationCore-win32-ia32/resources/app.asar ./temp/app
- echo Copying .bin folder
- mkdir /temp/app/node_modules/.bin/
- cp -r /scripts/builds/.bin /temp/app/node_modules/.bin/
- echo Repacking app.asar
- asar pack ./temp/app ./dist/translationCore-win32-ia32/resources/app.asar
- node scripts/builds/build-win-installer.js
- echo Deleting temp
- rm -rf temp
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: vWCAoegCLLKDouMLDGUwb8P4CxcTynLYTtZH2CyEkru5Eucl9a9OPy16j0AxOQD1FxKWwbjCQ4MR4iISyNKPxZBwa9diGRjSQfV2ZqxsfaSECZTIYMFe6sMjPAnRSSnGz/0IAmsTJJMTSedNf8tM2fklODdwk2x/v4CGOjiIjcFpGgJ0iQFSt/K9CAjFhH4Ik7VKUwlcTQND0mXFZlTJKOsfZJgvp7zKdAGzB55V3uHJqLSjtDb70QYdSe4EWV/UVA+6R4bPr6+uxYJpggJD8dYo0As+G89fmscLucHqwKUs9qRyPkl4NdUlrcY+Xbr7jqEosUOnNJcLdfUjK57R04oAnRaVrz/iL2mHdosQlqFNn5RHa6u2FrHqRXAkb73fZqynnSeRq32s1Q2ysnCeHj6rYl078DuFm19zQ1cZxLK7EoM3BC54TPcZkQDUxkA301I36lJrxUdgt07AdEy4Dxsy5CcUvdsGbHeny/i80m2936uaRbaNg5uLmBswZScRQta4Bw+gywYwdD68lG96B7mPe9rz3Z2YXN1awH/0tyAztDsIxKQzx4TIFzYMVsgx7yb9r2xf4c5Vz56kr2NOZHym0fc/k1LGbC5Fc11lNhQ6IwU+psjl80Y5oacioVszsQ14+Ab/BavX5uk2sHeMQ/3zgfhB9twqt8dgsXXOYbI=
  file: "./dist/translationCore-win32-ia32/installer/translationCoreSetup.exe"
  on:
    repo: unfoldingWord-dev/translationCore
    branch: ih-travis-builds
